### ISSUE TITLE
Issue: How to compare

### ISSUE THREAD

**Issue by linuxpham** [roryk/bcbio.rnaseq#11]
Hi @roryk ,

I would like the tool to compare different groups using deseq, edgeR,.. What is the field in the config file that assigns samples into different groups ?

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

There needs to be some metadata about the samples that was included in the bcbio-nextgen run, it looks from your project-summary.yaml file that there wasn't anything set so you'd have to add it. If you edit the project-summary.yaml file and add metadata for each sample, then delete the project-summary.csv and the summary directory, and then re-run bcbio-rnaseq adding a model formula at the end with -f "~your_factor", it will work. 

Alternatively it is probably easier to just work through one of the vignettes starting from the counts and the summarydata object in the qc-summary.Rmd file; you are going to have to do something different than what bcbio-rnaseq does because it looks like there aren't really replicates in your data: http://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.pdf is a good place to start.

**Comment by linuxpham** [comment]
Hi @roryk ,

It is Ok now !

Thanks !!!

**Comment by roryk** [comment]
Great!
